spring.application.name=vendedor
server.port=8083
spring.datasource.url=jdbc:postgresql://ep-spring-breeze-apdryawv-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Z6UXHiYk7SVw
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci\u00f3n de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always
server.error.include-binding-errors=always

logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.validator=DEBUG


#-----habilitar la documentacion 
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
#---configurar prefijo de api 
springdoc.api-docs.path=/doc/v3/api-docs

#--ruita de acceso al navegador 
springdoc.swagger-ui.path=/doc/swagger-ui.html
##descativsar el favicon
springdoc.swagger-ui.disable-favicon=true



#http://localhost:8083/doc/swagger-ui/index.html